### ISSUE TITLE
BUG: Time MODE is very slow on any device and cannot set the time

### ISSUE THREAD

**Issue by kesylo** [farhoudshapouran/react-native-ui-datepicker#31]
Hello @farhoudshapouran 
After some other tests, I noticed that when mode = "time", the time selector wheel is very slow. I checked on the following devices:
- Google Pixel 6
- Iphone 12 PRO
So I dont think its the device that is slow.
Also I cannot set a time. it always result to no time set as you can see in the video below
btw i'm still using the basic example from your docs:
`<DateTimePicker
	value={value}
	mode={"time"}
	onValueChange={(date) => setValue(date)}
/>`
Package version: 1.0.7

https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/32457792/66068de3-fc51-41e2-83c7-d879b84ef910

**Comment by farhoudshapouran** [comment]
The problem with the time mode was fixed in the latest version, the time picker is slow in the emulator, but it has better performance on a real device

**Comment by kavinraju** [comment]
I am also facing the same issue. Its very slow in actual device (both android & iOS), but in simulator(iPhone 15) its working better than actual device, which is again little laggy. I have noticed few of the previous issues mentioning that this issue is fixed, but it's still persisting.

**Comment by Epiled** [comment]
I am also experiencing the same issue when I try running tests on both an Android device and an Android simulator.
